# Use the official image as a parent image
FROM httpd:2.4

# Set the maintainer label
LABEL maintainer="your-email@example.com"

# Copy the frontend's dist folder to Apache's htdocs
COPY dist/ /usr/local/apache2/htdocs/

# Copy the custom Apache config
COPY frontend.conf /usr/local/apache2/conf/httpd.conf

# Explicitly specify the command to run Apache in the foreground
CMD ["httpd-foreground"]