version: '3.7'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "5000:80"
    environment:
      - FLASK_ENV=development
    depends_on:
      - database

  
  database:
    image: postgres:13
    container_name: db
    ports:
      - "5432:5432"
    env_file:
    - .env