version: '3'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "5000:80"
    environment:
      - FLASK_ENV=development

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
    volumes:
      - ./frontend/dist:/usr/local/apache2/htdocs/
    ports:
      - "3000:80"
