# Use Ubuntu as base image
FROM ubuntu:latest

# Set environment variables to non-interactive (this prevents some prompts)
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary packages
RUN apt-get update && apt-get install -y \
    postgresql-12 \
    postgresql-contrib-12 \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Switch to the postgres user
USER postgres

# Initialize the database. This step creates the initial database structure on disk.
RUN /usr/lib/postgresql/12/bin/initdb -D /var/lib/postgresql/12/main

# Modify the pg_hba.conf file to set proper permissions. This is a basic example to get started.
RUN echo "host all  all    0.0.0.0/0  md5" >> /var/lib/postgresql/12/main/pg_hba.conf

# Modify the postgresql.conf file to accept connections from any IP address.
RUN echo "listen_addresses='*'" >> /var/lib/postgresql/12/main/postgresql.conf

# Expose PostgreSQL's default port
EXPOSE 5432

# Command to run PostgreSQL server
CMD ["/usr/lib/postgresql/12/bin/postgres", "-D", "/var/lib/postgresql/12/main"]